PA EQU 30H
PB EQU 31H
CA EQU 32H
CB EQU 33H

IMR EQU 21H
EOI EQU 20H
INT0 EQU 24H
N_F10 EQU 10

ORG 40
DW RUT_F10

ORG 1000H
FIN_LEER DB 0
LARGO DB 0
CADENA DB ?

ORG 3200H
RUT_F10: PUSH AX
         MOV AL, 0FFH
         OUT IMR, AL
         MOV FIN_LEER, 1
         MOV AL, EOI
         OUT EOI, AL
         POP AX
         IRET

ORG 3000H
LEE_CADENA:
CLI
MOV AL, 0FEH
OUT IMR, AL
MOV AL, N_F10
OUT INT0, AL
STI
MOV BX, OFFSET CADENA
MOV LARGO, 0
SIGUE: INT 6
       INC BX
       CMP FIN_LEER, 0
       JZ SIGUE
       RET
ORG 2000H
CALL LEE_CADENA
MOV AL, 0FDH ; STROBE SALIDA (0), BUSY ENTRADA (1)
OUT CA, AL
MOV AL, 0 ; PUERTO DE DATOS TODO SALIDA
OUT CB, AL

; INICIALIZO STROBE EN 0
IN AL, PA
AND AL, 11111101B
OUT PA, AL
MOV CL, LARGO
MOV BX, OFFSET CADENA
; ESPERO QUE BUSY = 0
POLL: IN AL, PA
      AND AL, 01H ; 1000 0000
      JNZ POLL
      ; SE QUE BUSY ES 0, MANDAR CARACTER
      MOV AL, [BX]
      OUT PB, AL
      ; MANDAR FLANCO ASCENDENTE DE STROBE
      IN AL, PA
      OR AL, 00000010B
      OUT PA, AL
      ; STROBE EN 0
      IN AL, PA
      AND AL, 11111101B
      OUT PA, AL
      INC BX
      DEC CL
      JNZ POLL
INT 0
END
