ORG 1000H
CERO DB "CERO  " ; TODOS LOS NOMBRES TIENEN 6 CARACTERES PARA
     DB "UNO   " ; FACILITAR POSICIONARNOS AL IMPRIMIR
     DB "DOS   "
     DB "TRES  "
     DB "CUATRO"
     DB "CINCO "
     DB "SEIS  "
     DB "SIETE "
     DB "OCHO  "
     DB "NUEVE "
MSJ  DB "INGRESE UN NUMERO:"
FIN  DB ?

ORG 1500H
NUM DB ?

ORG 2000H
MOV CL, 0 ; CONTADOR DE VECES QUE INGRESA EL VALOR 0 DE FORMA
; CONSECUTIVA
OTRO: MOV BX, OFFSET MSJ
      MOV AL, OFFSET FIN - OFFSET MSJ
      INT 7 ; IMPRIMO MENSAJE EN PANTALLA PIDIENDO UN NUMERO
      MOV BX, OFFSET NUM
      INT 6 ; LEO UN NUMERO Y QUEDA GUARDADO EN NUM
      CMP NUM, 30H
      JNZ NO_CERO
      INC CL ; SI VINO UN VALOR 0 INCREMENTO EL CONTADOR
      JMP SEGUIR
NO_CERO: MOV CL, 0 ; COMO NO VINO CERO REINICIALIZO CL
SEGUIR: MOV BX, OFFSET CERO ; LA DIRECCIÓN BASE SERÁ LA DEL 
; PRIMER MENSAJE "CERO  "
        MOV AL, 6 ; SE VA A IMPRIMIR 6 CARACTERES, TODOS TIENEN
; EL MISMO LARGO
LOOP: CMP NUM, 30H
      JZ IMPRIME ; SI ES EL VALOR ADECUADO, IMPRIMO EN PANTALLA
; EL NOMBRE DEL NUMERO
      ADD BX, 6 ; SI NO ES EL VALOR ADECUADO ME POSICIONO EN EL SIGUIENTE NOMBRE
      DEC NUM ; AL LLEGAR NUM A 0 ESTARÁ POSICIONADO EN EL NOMBRE QUE CORRESPONDE
      JMP LOOP
IMPRIME: INT 7
         CMP CL, 2
         JNZ OTRO ; SI NO SE INGRESÓ DOS VECES SEGUIDAS EL 0, SIGUE PROCESANDO
         INT 0
END
