PA EQU 30H
CA EQU 32H
PATRON EQU 10000001B

ORG 1000H
CADENA DB "ACTIVADO"
FIN_CADENA DB ?

ORG 2000H
      MOV AL, 255 ; PA: ENTRADAS
      OUT CA, AL
      MOV BX, OFFSET CADENA
LOOP: IN AL, PA
      CMP AL, PATRON ; VERIFICO QUE SEA EL MISMO PATRÓN
      JNZ LOOP
      MOV AL, OFFSET FIN_CADENA - OFFSET CADENA
      INT 7
      JMP LOOP

INT 0
END