EOI EQU 20H
IMR EQU 21H
INT1 EQU 25H
CONT EQU 10H
COMP EQU 11H
ORG 1000H
MSJ  DB  "NO DEBO PROGRAMAR EN ASSEMBLER"
SALTOLINEA  DB  13
FIN  DB  ?
ORG 32 ; 8 * 4 = 32
DIR_MANEJADOR  DW  3000H
ORG 3000H
MANEJADOR:  MOV AL, 0
            OUT CONT, AL
            ; EJECUTA CADA 5 SEGUNDOS
            MOV BX, OFFSET MSJ
            MOV AL, OFFSET FIN - OFFSET MSJ
            INT 7
            MOV AL, 20H
            OUT EOI, AL
            IRET
ORG 2000H
CLI
MOV AL, 0FDH ; 1111 1101
OUT IMR, AL
MOV AL, 8
OUT INT1, AL
MOV AL, 0
OUT CONT, AL
MOV AL, 5
OUT COMP, AL
STI
LOOP: JMP LOOP
INT 0
END