; ejercicio 5
ORG 1000H
INGRESO  DB  "INGRESE CLAVE:"
ACC_OK   DB  "ACCESO PERMITIDO"
ACC_FAIL DB  "ACCESO DENEGADO"
ACC_OUT  DB  "ACCESO BLOQUEADO"
ERRORES  DB  0
CLAVE    DB  "PASS"
CLAVEING DB ?

ORG 2000H
INICIO:  MOV BX, OFFSET INGRESO
         MOV AL, OFFSET ACC_OK - OFFSET INGRESO
         INT 7
         MOV CL, 4
         MOV BX, OFFSET CLAVEING
LEER:    INT 6
         INC BX
         DEC CL
         JNZ LEER
         MOV DX, 3
COMP:    MOV BX, OFFSET CLAVE
         ADD BX, DX
         MOV AL, [BX]
         MOV BX, OFFSET CLAVEING
         ADD BX, DX
         CMP [BX], AL
         JNZ ERROR
         DEC DX
         JNZ COMP
         MOV BX, OFFSET ACC_OK
         MOV AL, OFFSET ACC_FAIL - OFFSET ACC_OK
         INT 7
         JMP FINAL
ERROR:   INC ERRORES
         CMP ERRORES, 5
         JZ ECHAR
         MOV BX, OFFSET ACC_FAIL
         MOV AL, OFFSET ACC_OUT - OFFSET ACC_FAIL
         INT 7
         JMP INICIO
ECHAR:   MOV BX, OFFSET ACC_OUT
         MOV AL, OFFSET ERRORES - OFFSET ACC_OUT
         INT 7
FINAL:   HLT

END