CONT    EQU 10H
COMP    EQU 11H
ID_CLK  EQU 4
EOI     EQU 20H
IMR     EQU 21H
INT1    EQU 25H
PB      EQU 31H
CB      EQU 33H

ORG 1000H
MSJNRO       DB  "Ingrese el nro de luz que nunca se encendio"
GANASTE      DB  "GANASTE"
SECUENCIA    DB  00000001b, 00000100b, 00000010b, 00001000b, 10000000b, 00100000b, 00010000b
NO_PRENDE    DB  6
NROINGRESADO DB ?
FLAG         DB 0

ORG 16
DIR_CLK DW RUT_CLK

ORG 3000H
CMP CL, 0
JZ FIN
MOV AL, [BX]
OUT PB, AL
INC BX
DEC CL
FIN:    MOV AL, 0
        OUT CONT, 0
        MOV AL, EOI
        OUT EOI, AL
        MOV AL, 0
        OUT IMR, AL
        IRET

ORG 2000H
MOV BX, OFFSET SECUENCIA
MOV CL, OFFSET NO_PRENDE - OFFSET SECUENCIA
MOV AL, 00H
OUT CB, AL
MOV AL, 00H
OUT PB, AL

CLI
MOV AL, 0FDH
OUT IMR, AL
MOV AL, 0
OUT CONT, AL
MOV AL, 1
OUT COMP, AL
MOV AL, ID_CLK
OUT INT1, AL
STI
MOV BX, OFFSET MSJNRO
MOV AL, OFFSET GANASTE - OFFSET MSJNRO
INT 7
MOV BX, OFFSET NROINGRESADO
INT 6
MOV DX, [BX]
CMP DX, NO_PRENDE
JZ GANA
JMP TERMINAR

GANA:   MOV BX, OFFSET GANASTE
        MOV AL, OFFSET SECUENCIA - OFFSET GANASTE
        INT 7
TERMINAR: INT 0
          END