ORG 1000H
VECTOR DW 50, 15, 25, 12, 4, 2, 4, 3, 1
FIN_VECTOR DB ?
CONTADOR_PARES DW 0
CONTADOR_IMPARES DW 0
MSJ_PARES DB "Ganan los pares"
MSJ_IMPARES DB "Ganan los impares"
FIN_MSJ DB ?

ORG 3000H
ES_PAR: AND AX, 0001H ; MOD 2 = 0
        JZ ES
        MOV DX, 0
        INC CONTADOR_IMPARES
        JMP FIN
ES:     MOV DX, 1
        INC CONTADOR_PARES
FIN:    RET

ORG 3100H
CONTAR_PARES: MOV AX, [BX] ; AX = VALOR DE VECTOR
PUSH AX
CALL ES_PAR
ADD BX, 2
POP AX
SUB CL, 2
JNZ CONTAR_PARES
MOV AX, CONTADOR_PARES
RET

ORG 2000H
MOV BX, OFFSET VECTOR
MOV CL, OFFSET FIN_VECTOR - OFFSET VECTOR
PUSH CX
PUSH BX
CALL CONTAR_PARES
POP BX
POP CX    
CMP AX, CONTADOR_IMPARES
JS GANAN_IMPARES
GANAN_PARES:   MOV BX, OFFSET MSJ_PARES
               MOV AL, OFFSET MSJ_IMPARES - OFFSET MSJ_PARES
               INT 7
               JMP TERMINAR
GANAN_IMPARES: MOV BX, OFFSET MSJ_IMPARES
               MOV AL, OFFSET MSJ_IMPARES - OFFSET FIN_MSJ
               INT 7
TERMINAR:      INT 0
               END