PA EQU 30H
PB EQU 31H
CA EQU 32H
CB EQU 33H

ORG 1000H
MENSAJE DB "Imprimiendo en la impresora con el PIO"
FIN DB ?

ORG 2000H
MOV AL, 11111101B ; Strobe de salida, Busy de entrada
OUT CA, AL

MOV AL, 0 ; todos de salida
OUT CB, AL

; Recorremos el String
MOV BX, OFFSET MENSAJE
POLL: IN AL, PA
  AND AL, 1
  JNZ POLL ; MIENTRAS NO ESTÉ LIBRE, SIGO CONSULTANDO

  ; LA IMPRESORA ESTÁ LIBRE!
  MOV AL, [BX]
  OUT PB, AL
  
  ; MANDO STROBE EN 1
  IN AL, PA ; TOMAMOS EL ESTADO
  OR AL, 2 ; FUERZO STROBE A 1
  OUT PA, AL

  ; MANDO STROBE EN 0
  IN AL, PA ; TOMAMOS EL ESTADO
  AND AL, 0FDH ; FUERZO EL STROBE EN 0
  OUT PA, AL
  
  INC BX
  CMP BX, OFFSET FIN
  JNZ POLL

INT 0
END